run:
  timeout: 15m
  tests: true

linters:
  enable:
    - goimports
    - gofmt
    - gofumpt
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - gochecknoinits
    - goconst
    - tagliatelle
    - tparallel
    - testifylint
    - misspell
    - unused
    - ineffassign

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoinits
