name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOLANGCI_LINT_VERSION: v1.60.1

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.0
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
          stable: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: ./...
