name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: app
  POSTGRES_URL: postgres://postgres:password@localhost:5432/app?sslmode=disable

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.0
        env:
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{env.POSTGRES_DB}}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=rootpassword" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.0
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: go test ./... -v
